added MarkPersistentFlagRequired since namespace is added as a persistentFlag
it now throws an error when namespace flag is not set e.g. :

Error: required flag(s) "namespace" not set